apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../flux-modules/flux-system-extra/kustomization-flux-system-extra.yaml
  - ../../flux-modules/monitoring/kustomization-monitoring.yaml
  - ../../flux-modules/kube-system/kustomization-kube-system.yaml
